const commonlyForgotten = [
  "Birthdays",
  "Anniversaries",
  "Passwords",
  "Appointments",
  "Names",
  "Where they put their keys",
  "Phone numbers",
  "To reply to texts or emails",
  "Directions",
  "Where they parked their car",
  "To buy milk",
  "To pay bills",
  "Doctor's appointments",
  "To take medicine",
  "Taking out the trash",
  "To feed the pet",
  "Meeting times",
  "The date",
  "To lock the door",
  "Grocery lists",
  "Homework",
  "To put the toilet seat down",
  "Words mid-sentence",
  "Watering the plants",
  "To charge their phone",
  "Returning borrowed items",
  "To put gas in the car",
  "Washing the dishes",
  "Sending a thank you note",
  "To buy a gift for an event",
  "The title of a movie",
  "Returning calls",
  "To turn off the stove",
  "Setting the alarm",
  "To drink enough water",
  "Lyrics of a song",
  "Brushing teeth",
  "Cleaning up after themselves",
  "To check the mail",
  "To pack lunch for work",
  "To close the garage door",
  "To turn off the lights",
  "The plot of a book",
  "Their glasses on their head",
  "To call their parents",
  "Important documents for a meeting",
  "To put the laundry in the dryer",
  "Facts for a test",
  "To renew their driver's license",
  "To wash their hands",
  "To save their work on the computer",
  "To take the clothes out of the washing machine",
  "To take their vitamins",
  "To update their software",
  "To turn off the TV",
  "To bring their umbrella when it's cloudy",
  "To take food out of the freezer",
  "Their wallet at home",
  "Names of acquaintances",
  "To turn off the coffee maker",
  "Cleaning up after the pet",
  "To bring reusable bags to the store",
  "Ordering items online",
  "Their lunch in the fridge",
  "To mail a letter",
  "Where they left their shoes",
  "Their computer charger at work",
  "To close the windows when it's raining",
  "To bring their gym clothes",
  "To floss",
  "Doing their hair in the morning",
  "To sign a card",
  "Packing socks for a trip",
  "To write in their journal",
  "To do their stretches",
  "To replace the batteries in the smoke detector",
  "Their phone on silent",
  "The pizza in the oven",
  "To post on social media",
  "Setting their fantasy football lineup",
  "To cancel a free trial",
  "Downloading an important file",
  "To put on sunscreen",
  "To remove their makeup before bed",
  "To put the cap back on the toothpaste",
  "To back up their data",
  "To put their phone on charge",
  "Their coffee on the roof of their car",
  "Where they put their ticket",
  "The combination to their lock",
  "To defrost the chicken",
  "To clean their glasses",
  "To bring the tickets for the show",
  "Their reusable water bottle at home",
  "To clean their phone screen",
  "To turn off the data when connecting to WiFi",
  "To bring their grocery list",
  "To dry clean their clothes",
  "To wipe down gym equipment",
  "Their headphones at home",
  "To log out of their accounts",
  "Where they put their book",
  "To bring a towel to the beach",
  "To renew their passport",
];

export default commonlyForgotten;
