const forgetfulnessReasons = [
	"I've been really stressed out lately, maybe that's why I forgot.",
	"I didn't get enough sleep last night; that's probably why I'm forgetting things.",
	"With all this multitasking, it's no wonder I forgot.",
	'My mind was elsewhere when I was supposed to remember, that must be why I forgot.',
	"I've been skipping meals lately, maybe that's affecting my memory.",
	"I'm so worried about the presentation tomorrow, I completely forgot about the meeting today.",
	"I've been on the computer too much lately, maybe I need a break.",
	'I think my medication might be affecting my memory.',
	"I probably forgot because I didn't pay enough attention when it was mentioned.",
	"I haven't been exercising much lately, could that be why I'm forgetting things?",
	"I've been feeling down recently, maybe my forgetfulness is a symptom of depression.",
	"I've been consuming too much alcohol recently, which could be affecting my memory.",
	"I've been rushing around so much, it's no wonder I can't remember.",
	"That information wasn't important to me, so I probably didn't make an effort to remember.",
	"I've been so focused on my new project, I completely forgot about the old one.",
	'I think the lack of Vitamin B12 in my diet is affecting my memory.',
	"I'm constantly distracted by my phone, that's probably why I forgot.",
	"I've been trying to do too many things at once, so something had to slip.",
	'My head was full of other thoughts when I was supposed to remember that.',
	"I didn't sleep well last night, that must be why I forgot.",
	"I've been so busy lately, it's not surprising that I forgot.",
	"There's so much on my mind, I must've pushed that memory out.",
	"I didn't put it in my calendar, so I forgot.",
	"I'm just not drinking enough water, maybe that's affecting my cognitive functions.",
	"I haven't had time to relax and clear my mind, maybe that's why I'm forgetting things.",
	"There's a lot of noise around me, it's hard to focus.",
	"I have too many things on my to-do list, I can't remember everything.",
	"I've been ignoring my health issues, which may be causing memory problems.",
	"The room is so cluttered, it's hard to keep track of everything.",
	"I've been feeling anxious recently, that must be affecting my memory.",
	"I'm getting older, forgetfulness is just part of the process.",
	"I didn't organize my thoughts, so I forgot.",
	"I've been drinking too much coffee, perhaps it's affecting my sleep and memory.",
	"I don't have a good routine in place, that's why I keep forgetting things.",
	"There's a lot going on in my life, it's overwhelming.",
	"I probably didn't encode that memory properly.",
	"I've been on autopilot recently, not fully conscious of my actions.",
	"I've been neglecting my mental health, which could be causing memory issues.",
	"My surroundings are always changing, so it's hard to remember things.",
	"I didn't repeat the information to myself, that's why I forgot.",
	"I've been spending too much time indoors, maybe I need some fresh air.",
	"I keep putting off my check-ups, perhaps there's an underlying health issue.",
	"I've been feeling a bit off lately, it must be affecting my memory.",
	"I haven't been challenging my brain enough, it's getting lazy.",
	"I didn't associate that memory with anything, so it didn't stick.",
	"I've been neglecting my social life, perhaps the lack of interaction is affecting my memory.",
	"I've been trying to suppress my emotions, maybe that's why I'm forgetting things.",
	"There's been too much screen time lately, it must be straining my brain.",
	"I didn't have a clear mind when I was supposed to remember that.",
	'My mind was on my personal problems, not on what I was supposed to remember.',
	"I've been really stressed out lately, maybe that's why I forgot.",
	"I didn't get enough sleep last night; that's probably why I'm forgetting things.",
	"With all this multitasking, it's no wonder I forgot.",
	'My mind was elsewhere when I was supposed to remember, that must be why I forgot.',
	"I've been skipping meals lately, maybe that's affecting my memory.",
	"I'm so worried about the presentation tomorrow, I completely forgot about the meeting today.",
	"I've been on the computer too much lately, maybe I need a break.",
	'I think my medication might be affecting my memory.',
	"I probably forgot because I didn't pay enough attention when it was mentioned.",
	"I haven't been exercising much lately, could that be why I'm forgetting things?",
	"I've been feeling down recently, maybe my forgetfulness is a symptom of depression.",
	"I've been consuming too much alcohol recently, which could be affecting my memory.",
	"I've been rushing around so much, it's no wonder I can't remember.",
	"That information wasn't important to me, so I probably didn't make an effort to remember.",
	"I've been so focused on my new project, I completely forgot about the old one.",
	'I think the lack of Vitamin B12 in my diet is affecting my memory.',
	"I'm constantly distracted by my phone, that's probably why I forgot.",
	"I've been trying to do too many things at once, so something had to slip.",
	'My head was full of other thoughts when I was supposed to remember that.',
	"I didn't sleep well last night, that must be why I forgot.",
	"I've been so busy lately, it's not surprising that I forgot.",
	"There's so much on my mind, I must've pushed that memory out.",
	"I didn't put it in my calendar, so I forgot.",
	"I'm just not drinking enough water, maybe that's affecting my cognitive functions.",
	"I haven't had time to relax and clear my mind, maybe that's why I'm forgetting things.",
	"There's a lot of noise around me, it's hard to focus.",
	"I have too many things on my to-do list, I can't remember everything.",
	"I've been ignoring my health issues, which may be causing memory problems.",
	"The room is so cluttered, it's hard to keep track of everything.",
	"I've been feeling anxious recently, that must be affecting my memory.",
	"I'm getting older, forgetfulness is just part of the process.",
	"I didn't organize my thoughts, so I forgot.",
	"I've been drinking too much coffee, perhaps it's affecting my sleep and memory.",
	"I don't have a good routine in place, that's why I keep forgetting things.",
	"There's a lot going on in my life, it's overwhelming.",
	"I probably didn't encode that memory properly.",
	"I've been on autopilot recently, not fully conscious of my actions.",
	"I've been neglecting my mental health, which could be causing memory issues.",
	"My surroundings are always changing, so it's hard to remember things.",
	"I didn't repeat the information to myself, that's why I forgot.",
	"I've been spending too much time indoors, maybe I need some fresh air.",
	"I keep putting off my check-ups, perhaps there's an underlying health issue.",
	"I've been feeling a bit off lately, it must be affecting my memory.",
	"I haven't been challenging my brain enough, it's getting lazy.",
	"I didn't associate that memory with anything, so it didn't stick.",
	"I've been neglecting my social life, perhaps the lack of interaction is affecting my memory.",
	"I've been trying to suppress my emotions, maybe that's why I'm forgetting things.",
	"There's been too much screen time lately, it must be straining my brain.",
	"I didn't have a clear mind when I was supposed to remember that.",
	'My mind was on my personal problems, not on what I was supposed to remember.',
	"I haven't been challenging my brain enough, it's getting lazy.",
	"I didn't associate that memory with anything, so it didn't stick.",
	"I've been neglecting my social life, perhaps the lack of interaction is affecting my memory.",
	"I've been trying to suppress my emotions, maybe that's why I'm forgetting things.",
];

export default forgetfulnessReasons;
